// Shared contracts for the app-wide hand-controlled cursor.
//
// Owned by Agent 4 (setup/integration). Agents 1-3 implement against these
// types but do not edit this file; if a contract doesn't fit, flag it in
// your handoff instead of changing it here.
//
// REVISION 4 -- replaces thumb/index "pinch" with index/middle "select" as
// the one-hand click/drag gesture; thumb/index pinch is now used ONLY as the
// precursor to two-hand zoom (unchanged mechanism, no longer publicly
// exposed per-hand). Adds two-second dwell (hover) activation on sidebar nav
// icons, and a user-customizable interaction color.
//
// REVISION 5 -- fixes two visual bugs (color-swatch CSS, and cursor
// engaged/neutral feedback not reflecting the confirmed gesture state via
// the new `isSelecting` field) and merges dwell with select into ONE
// rate-based accelerated-dwell system for sidebar nav targets (see the
// DWELL doc below -- this supersedes Revision 4's "select cancels dwell"
// behavior). Adds a user-customizable cursor shape. See
// HAND_INTERACTION_PLAN.md Revision 5 for the full task breakdown.
//
// Pipeline: TrackingAdapter (Agent 1: camera + MediaPipe) -> GestureProcessor
// (Agent 2: mirroring, control-region mapping, smoothing, SELECT lifecycle,
// two-hand zoom kinematics, select/pinch priority) -> hand-pointer
// integration (Agent 4: hit-testing, hover/activation/drag, rate-based dwell
// timer, zoom context-gating, color/shape settings) -> app-wide overlay +
// calibration UI (Agent 3), consuming the integration layer's state.

/** One raw hand landmark in MediaPipe's normalized image-space coordinates. */
export interface HandLandmark {
  x: number; // [0,1], left->right of the RAW camera frame (unmirrored)
  y: number; // [0,1], top->bottom
  z: number; // hand-relative depth; smaller = closer to camera
}

export type Handedness = "Left" | "Right";

/**
 * One detected hand within a HandFrame.
 *
 * IDENTITY: `handedness` IS this hand's stable identity across frames --
 * MediaPipe's per-frame detection array order is NOT stable (which index is
 * "hand 0" can swap frame to frame), so nothing may key a hand by array
 * position. A hand whose handedness comes back null (rare, low-confidence
 * classification) is still included here for completeness but MUST be
 * excluded from primary/secondary role assignment and two-hand zoom in
 * GestureProcessor -- there is no reliable identity to track it by. This is
 * a deliberate, documented simplification (no positional re-identification
 * heuristic) rather than a general multi-object tracker.
 */
export interface TrackedHand {
  landmarks: HandLandmark[]; // exactly 21, raw, unmirrored
  handedness: Handedness | null;
}

/**
 * One tracked frame, emitted by a TrackingAdapter at camera/model frame rate
 * (not necessarily every animation frame).
 *
 * TIMESTAMP SEMANTICS: `timestamp` is `performance.now()` (monotonic
 * milliseconds since page load / navigation start) captured the moment the
 * adapter receives this result from the model. Never Date.now(), never a
 * value derived only from the model's internal counters. It must strictly
 * increase frame over frame. Consumers use it only to measure elapsed time
 * between frames (e.g. smoothing, staleness, dwell timing), never as a
 * wall-clock date, and never assume a fixed frame rate -- read real dt.
 *
 * `hands` holds 0-2 entries, raw and UNMIRRORED: exactly what MediaPipe
 * returns for the camera's actual image, before any left/right flip or
 * control-region remapping. GestureProcessor (Agent 2) is the only place
 * that mirrors or remaps them into viewport space. Do not mirror or remap in
 * the tracking adapter or anywhere in the UI/integration layer.
 *
 * `frameWidth`/`frameHeight` are the camera's actual capture resolution in
 * pixels (`video.videoWidth`/`videoHeight`), needed to measure two-hand
 * separation in an aspect-correct way -- landmark x/y are each normalized to
 * [0,1] independently, so a 0.1 gap in x and a 0.1 gap in y do NOT cover the
 * same physical distance unless the frame is square.
 */
export interface HandFrame {
  timestamp: number;
  hands: TrackedHand[];
  frameWidth: number;
  frameHeight: number;
}

export type TrackingStatus = "idle" | "loading" | "tracking" | "no-hand" | "error";

/**
 * STALE-FRAME DETECTION
 *
 * Camera frames can silently stop arriving (tab backgrounded and throttled,
 * camera device unplugged, MediaPipe worker wedged, the MediaStream track
 * ending) without any error event firing. A TrackingAdapter must not rely on
 * frame delivery alone to notice this -- it must run a watchdog on its own
 * timer (setInterval, decoupled from the camera's own frame callback) that
 * checks `performance.now() - lastFrameAt` on a fixed clock, independent of
 * whether frames are still coming in.
 *
 * Rules:
 * - A fresh frame (age < STALE_FRAME_MS) with `hands.length === 0` means the
 *   camera pipeline is fine but no hand is visible -> status "no-hand".
 * - No frame delivered for >= STALE_FRAME_MS means the pipeline itself has
 *   stalled, regardless of what the last frame said -> status "error". This
 *   is the only way staleness is caught once frames stop arriving entirely.
 */
export const STALE_FRAME_MS = 500;

/** MediaPipe Hand Landmarker indices used by the gesture processor. */
export const LANDMARK = {
  WRIST: 0,
  THUMB_TIP: 4,
  INDEX_MCP: 5,
  INDEX_TIP: 8,
  MIDDLE_MCP: 9,
  MIDDLE_TIP: 12,
} as const;

export interface TrackingAdapter {
  start(): Promise<void>;
  stop(): void;
  /** Releases camera + model resources; the adapter is unusable after this. */
  cleanup(): void;
  onFrame(cb: (frame: HandFrame) => void): () => void; // returns unsubscribe
  onStatus(cb: (status: TrackingStatus) => void): () => void;
}

/**
 * A point in CSS pixels relative to the viewport's top-left corner --
 * exactly what `element.getBoundingClientRect()` / `clientX,clientY` use, so
 * it is directly comparable to hit-testing and existing layout without a
 * second conversion.
 */
export interface ViewportPoint {
  x: number;
  y: number;
}

/**
 * The one-hand gesture that drives ordinary click/drag/hover-activation:
 * bringing the INDEX_TIP and MIDDLE_TIP together, then separating them to
 * release. Replaces thumb/index pinch for this purpose as of Revision 4 --
 * thumb/index is reserved exclusively for two-hand zoom now (see the
 * priority rule on GestureProcessor below). Primary hand only.
 */
export type SelectEventType = "selectstart" | "selectmove" | "selectend" | "cancel";

export interface SelectEvent {
  type: SelectEventType;
  point: ViewportPoint;
  timestamp: number; // same monotonic clock as HandFrame.timestamp
}

/** Movement past this many CSS px (from the selectstart point) makes a held select a drag, not a click. */
export const DRAG_THRESHOLD_PX = 12;

/**
 * The comfortable-movement control region (GOAL 1, Revision 3): a rectangle
 * in RAW camera-normalized space (unmirrored, matching HandLandmark x/y)
 * that maps to the FULL viewport, so small hand movements near the body's
 * natural resting position reach every screen edge.
 *
 * All four fields are fractions of the camera frame, [0,1]. The rectangle is
 * `[centerX - width/2, centerX + width/2] x [centerY - height/2, centerY + height/2]`.
 * Only vertical position and size are meant to be user-adjustable (per GOAL
 * 1's calibration UI); centerX is expected to stay 0.5 in practice, but nothing
 * enforces that in the type.
 */
export interface ControlRegion {
  centerX: number;
  centerY: number;
  width: number;
  height: number;
}

/** Starting point (a tunable default, not a fixed rule -- see calibration UI). */
export const DEFAULT_CONTROL_REGION: ControlRegion = {
  centerX: 0.5,
  centerY: 0.5,
  width: 0.55,
  height: 0.55,
};

/** Two-hand pinch-to-zoom lifecycle. See GestureProcessor doc below for the full state machine. */
export type TwoHandZoomEventType = "zoomstart" | "zoomchange" | "zoomend" | "zoomcancel";

export interface TwoHandZoomEvent {
  type: TwoHandZoomEventType;
  /** current separation / separation at zoomstart. 1 at zoomstart; smoothed, dead-zoned, and rate-limited -- see GestureProcessor doc. */
  ratio: number;
  timestamp: number;
}

/**
 * GestureProcessor (owned by Agent 2)
 *
 * === Control-region mapping -- applies to `cursor` and `secondaryCursor` only ===
 *
 * Pipeline, in this exact order, using the PRIMARY hand's INDEX_TIP (raw,
 * unmirrored) and the current ControlRegion:
 *   1. `t = (rawX - (region.centerX - region.width/2)) / region.width`
 *      (same for y with height/centerY). This remaps the region's rectangle
 *      onto [0,1]; points outside it land outside [0,1].
 *   2. Clamp t to [0,1] on both axes -- this is what makes "small movements
 *      reach every edge" (points past the region's edge just stick to the
 *      viewport edge, they don't run out of range).
 *   3. Mirror x EXACTLY ONCE, here, nowhere else: `mirroredX = 1 - clampedX`.
 *      y is never flipped.
 *   4. Scale to viewport pixels read live (`window.innerWidth/innerHeight`)
 *      exactly as before -- unchanged, still handles resize with no listener.
 *
 * `secondaryCursor`: the same 4-step pipeline applied to the non-primary
 * hand's INDEX_TIP, when a second hand is tracked. Visual use only (two-hand
 * zoom markers) -- never fed into hit-testing or activation.
 *
 * `setControlRegion(region)`: if a gesture is in progress (primary
 * selecting, primary pinching, or two-hand zoom active), the new region must
 * be QUEUED and applied only once none of those are true -- applying it
 * mid-gesture would jump the mapped cursor discontinuously and could misfire
 * a drag-threshold check or a synthetic drag/orbit event downstream. Select/
 * pinch DETECTION themselves are unaffected by the region (see below), so
 * this queuing is the only place a region change could leak into behavior.
 *
 * === Select / pinch / raw geometry -- UNCHANGED by the region, by design ===
 *
 * Select-distance (INDEX_TIP/MIDDLE_TIP), pinch-distance (THUMB_TIP/
 * INDEX_TIP) hysteresis, and two-hand separation all use RAW landmark
 * positions (plus WRIST/INDEX_MCP/MIDDLE_MCP for hand-size/pose reference,
 * and frameWidth/frameHeight for aspect correction) -- never the
 * region-mapped, clamped cursor. Region calibration can never distort what
 * counts as a select or a pinch, or how far apart two hands are.
 *
 * MIRRORING (unchanged) applies once, in step 3 above, nowhere else.
 *
 * SMOOTHING (unchanged): EMA on cursor.x/y using real inter-frame dt. Not
 * reset by select/pinch state changes -- only by a primary/secondary
 * identity change or reset() -- so bringing the fingers together for a
 * select never itself pulls the cursor off target.
 *
 * === Primary/secondary hand selection (unchanged) ===
 *
 * The first identified hand (non-null handedness) observed after
 * idle/reset becomes PRIMARY and stays primary as a second hand joins --
 * introducing a second hand must never move `cursor` or reinterpret
 * `onSelectEvent`, which always refers to the primary hand only. If the
 * primary hand's identity is absent from a frame's `hands[]` and another
 * identified hand IS present, that hand is promoted to primary immediately
 * (no debounce -- documented simplification). A hand with null handedness
 * is never assigned a role.
 *
 * === SELECT gesture (index/middle), primary hand only ===
 *
 * Distance(INDEX_TIP, MIDDLE_TIP) normalized by a hand-size reference (the
 * same WRIST-to-INDEX_MCP distance already used for pinch, for consistency)
 * gives a scale-invariant ratio. Two independently tunable pieces, both with
 * documented defaults Agent 2 owns and may tune (these are internal
 * constants, not exposed in this contract):
 *
 * - Hysteresis: a CLOSE ratio and a looser RELEASE ratio (same enter/exit
 *   pattern as pinch), so the boundary doesn't flicker on landmark noise.
 * - STABILITY WINDOW: the close-transition (ratio crossing under the CLOSE
 *   threshold) must hold continuously for a short duration (a documented
 *   default in the tens of milliseconds) before it actually commits to
 *   "selecting" and fires `selectstart` -- a single noisy frame must not
 *   trigger it. Apply the same debounce symmetrically to the release
 *   transition. This is what satisfies "a deliberate open-to-closed
 *   transition: a newly detected hand with fingers already together must
 *   not immediately select anything" -- a hand that appears already-closed
 *   still has to hold that pose through the stability window before
 *   `selectstart` fires, same as a hand that closes while already tracked.
 *
 * - POSE CHECK (fist rejection): index/middle proximity alone can't
 *   distinguish a deliberate select from an ordinary closed fist (where
 *   every fingertip ends up close together). Before committing to
 *   `selectstart`, verify INDEX_TIP and MIDDLE_TIP are each still extended
 *   away from their own MCP (INDEX_MCP/MIDDLE_MCP) by at least a minimum
 *   fraction of hand size -- a fist curls fingertips back toward the palm,
 *   which this catches; a deliberate select brings two extended fingertips
 *   together without curling them. Document the exact formula and default
 *   threshold chosen in the handoff.
 *
 * === Select/pinch PRIORITY (this revision's key arbitration rule) ===
 *
 * On the PRIMARY hand ONLY: thumb/index pinch takes priority over
 * index/middle select. While the primary hand's own pinch-hysteresis reads
 * "pinching" (the same signal that feeds two-hand zoom below), select
 * cannot start on that hand -- its stability-window countdown does not even
 * begin. If select was ALREADY active (`selectstart` already fired) at the
 * moment the primary hand's pinch engages, immediately emit `cancel` for it.
 * Rationale: thumb/index pinching on the primary hand is what a user does to
 * set up two-hand zoom, and the two gestures can read as simultaneously true
 * on one hand during that setup (forming a pinch often partially curls the
 * middle finger too) -- without this rule, starting a pinch could spuriously
 * also fire a select/click. This is a superset of the literal minimum
 * ("two-hand zoom must suppress one-hand selection") in the same spirit as
 * the Revision 2 release-before-rearm deviation: it suppresses select
 * whenever the primary hand is pinching, not only once a second hand joins
 * and zoom actually starts, because the ambiguous hand pose exists either
 * way. Two-hand zoom's own kinematics (below) are entirely unaffected by
 * this rule and keep working exactly as before.
 *
 * === Two-hand pinch-to-zoom -- entirely context-free here, unchanged mechanism ===
 *
 * GestureProcessor tracks each identified hand's OWN pinch hysteresis
 * independently (thumb/index, same enter/exit ratios as always). It does
 * NOT know about the DOM, routes, or which control is hovered -- gating
 * ("only when the room viewer is the active context") is Agent 4's
 * integration-layer responsibility, applied to these events after the fact,
 * using live hover position (NOT a captured select target -- select and
 * pinch are independent gestures now, so there is no select-capture to key
 * zoom's context off of). This keeps GestureProcessor pure kinematics,
 * testable without a DOM. There is no public per-hand pinch event anymore
 * (nothing outside this module needs one-hand pinch state beyond the
 * priority rule above and the aggregate zoom signal below).
 *
 * State machine, keyed on `bothPinching = primary.pinching && secondary.pinching`
 * (only meaningful once both an identified primary AND secondary hand are
 * tracked):
 * - false -> true: `zoomstart`, ratio 1. Capture baseline separation: the
 *   aspect-corrected 2D distance between each hand's pinch point (midpoint
 *   of THUMB_TIP and INDEX_TIP), using `dx = (ax - bx) * (frameWidth/frameHeight)`,
 *   `dy = ay - by`, `separation = hypot(dx, dy)`. If the baseline is below a
 *   small epsilon (hands already on top of each other -- degenerate), do not
 *   start zoom at all.
 * - while true: each frame, recompute separation the same way, apply a
 *   small dead zone around ratio 1 (e.g. +-2%) so gesture-start jitter
 *   doesn't register as a zoom, rate-limit the ratio's frame-to-frame change
 *   (clamp how much it can move in one update, guarding against a single bad
 *   detection frame causing a snap), then EMA-smooth it, then emit
 *   `zoomchange` with the result. Never emit a ratio of 0 or a non-finite
 *   value -- guard divide-by-near-zero on both the baseline and any
 *   recomputation.
 * - true -> false via either hand's pinch releasing normally: `zoomend` with
 *   the final ratio.
 * - true -> false via either hand becoming untracked/unidentified: `zoomcancel`.
 *
 * `reset()` clears region-queue state, primary/secondary role assignment,
 * all per-hand select/pinch/smoothing state, and any in-progress zoom (as an
 * implicit cancel, no event needs emitting since there are no more
 * subscribers' expectations to honor across a reset).
 */
export interface GestureProcessor {
  update(frame: HandFrame): void;
  reset(): void;
  setControlRegion(region: ControlRegion): void;

  readonly cursor: ViewportPoint | null; // primary hand; null when no identified primary hand is tracked
  readonly secondaryCursor: ViewportPoint | null; // non-primary hand; null unless two identified hands are tracked. Visual use only.
  readonly isSelecting: boolean; // primary hand only
  onSelectEvent(cb: (event: SelectEvent) => void): () => void; // primary hand only, unaffected by a second hand

  readonly zoomRatio: number | null; // non-null only while both-hands-pinching (post dead-zone/smoothing)
  onZoomEvent(cb: (event: TwoHandZoomEvent) => void): () => void;
}

/**
 * Lifecycle of the hand cursor as a pointing device, owned by Agent 4's
 * integration layer (hit-testing + activation + drag adapters + dwell timer
 * + zoom context-gating) and read by Agent 3's overlay to drive hover/
 * select/activation/dwell/zoom feedback.
 *
 * - "idle": camera off (not opted in), or tracking not yet started.
 * - "pointing": tracking, cursor visible, no gesture in progress. Dwell
 *   (below) only ever progresses while phase is "pointing".
 * - "armed": select-down over an eligible target; not yet moved past
 *   DRAG_THRESHOLD_PX. Released here -> activation (a "click").
 * - "dragging": select held and moved past the threshold over a target that
 *   supports drag. Released here -> drag end, not a click.
 * - "zooming": two-hand pinch-to-zoom is active and being applied to the
 *   room viewer. One-hand selecting/dragging/orbiting are suppressed while
 *   in this phase (in practice this is rare to observe directly, since the
 *   GestureProcessor-level priority rule above already keeps select from
 *   being active on a pinching primary hand -- this phase mainly governs
 *   what the OVERLAY shows and that mouse-driven orbit stays disabled for
 *   the duration).
 *
 * hoverTarget is the nearest interactive ancestor under the PRIMARY cursor
 * (see hit-testing rule in HAND_INTERACTION_PLAN.md), already filtered for
 * disabled/hidden/out-of-modal elements, or null over empty space.
 */
export type HandPointerPhase = "idle" | "pointing" | "armed" | "dragging" | "zooming";

export interface HandPointerState {
  status: TrackingStatus;
  cursor: ViewportPoint | null;
  phase: HandPointerPhase;
  hoverTarget: HTMLElement | null;
  /**
   * The CONFIRMED gesture state from GestureProcessor.isSelecting, passed
   * through unchanged (Revision 5 fix -- see the note on this field's
   * history below). This is what cursor rendering must key off for
   * neutral-vs-engaged visuals, NOT `phase`: `phase` only becomes "armed"
   * once a target has been captured, so an overlay driven by `phase` alone
   * shows no visual difference at all when the user brings their fingers
   * together over empty space or a non-interactive area -- the gesture is
   * genuinely happening (isSelecting is true) even though there's nothing
   * to click. Do not compute this independently in the overlay (no separate
   * visual gesture detector) -- it must be this same confirmed signal.
   */
  isSelecting: boolean;
  /** Non-null only during "zooming"; for the overlay's two-hand markers/indicator. */
  twoHandZoom: { primaryPoint: ViewportPoint; secondaryPoint: ViewportPoint; ratio: number } | null;
  /** Non-null only while dwelling on an eligible target (see DWELL_ELIGIBLE_ATTR). */
  dwellTarget: HTMLElement | null;
  /** [0,1], meaningful only while dwellTarget !== null. Written every tracked frame -- see DwellEvent for discrete start/cancel/activate transitions. */
  dwellProgress: number;
}

/**
 * DWELL (hover) ACTIVATION, Revision 5 -- normal hover PLUS accelerated
 * selection on the SAME target. Supersedes the Revision 4 behavior where
 * bringing the fingers together cancelled dwell as "another gesture
 * beginning"; it now accelerates it instead, for dwell-eligible targets only.
 *
 * Owned entirely by Agent 4's integration layer: ONE logical timer is the
 * source of truth for both `dwellProgress` (continuous, for the overlay's
 * perimeter-tracing animation) and the discrete lifecycle events below -- an
 * animation completing on screen must never itself be what fires the
 * action; it only visualizes `dwellProgress` computed by that one timer.
 *
 * Eligibility is an explicit opt-in marker, `DWELL_ELIGIBLE_ATTR`, present
 * only on safe left-sidebar navigation controls (never global, never on a
 * destructive/action button) -- see the attribute's own doc.
 *
 * RATE-BASED PROGRESS (the core change this revision): progress is no
 * longer `(now - startTimestamp) / duration` (a single division), because
 * the duration can change mid-dwell. It is instead integrated every frame:
 *
 *   progress = clamp01(progress + dt / currentDuration)
 *   currentDuration = isSelecting ? DWELL_FAST_DURATION_MS : DWELL_DURATION_MS
 *
 * `dt` is the real elapsed time (frame.timestamp delta) since the last
 * integration step against the CURRENTLY COMMITTED target, never an assumed
 * frame rate. This formulation is what makes switching rates
 * (fingers together / apart) preserve accumulated progress with no jump or
 * reset -- there is only ever one accumulator, and only its rate of change
 * differs between the two modes. Clamp at 1 and activate exactly once.
 *
 * ONE-HAND-CLICK PIPELINE IS BYPASSED FOR DWELL TARGETS: when a select
 * gesture (`selectstart`) resolves to a target carrying
 * `DWELL_ELIGIBLE_ATTR`, the integration layer must NOT run its normal
 * capture/armed/click-or-drag handling for that gesture at all -- no target
 * capture, no phase change away from "pointing". `isSelecting` (above)
 * still flips true/false for cursor visuals, and dwell's own rate
 * integration reads it to switch speed, but the ONLY activation path for a
 * dwell target is dwell's own timer reaching 1. This is what satisfies "a
 * quick finger close/release must not bypass progress via the previous
 * release-to-click handler" and "release after dwell activation must not
 * click again" -- there is no captured target for the old click-on-release
 * path to act on, so it structurally cannot double-fire regardless of
 * timing, including across a navigation the dwell activation itself just
 * caused (a held gesture cannot "spill into" a stale release-click on the
 * new screen, because no click-on-release path exists for this gesture in
 * the first place). Every other control keeps the ordinary select
 * click/drag pipeline completely unchanged.
 *
 * Because dwell-eligible gestures never leave `phase === "pointing"`, dwell
 * keeps its existing phase-gate (`phase === "pointing"`) as the top-level
 * eligibility check for "is any OTHER gesture active" (two-hand zoom,
 * dragging, or a select in progress on some other, non-dwell target) --
 * unchanged from Revision 4.
 *
 * Target-change debounce ("allow slight cursor jitter without repeatedly
 * resetting progress, but never let that tolerance activate a neighboring
 * target"): progress accumulates strictly against ONE frozen target
 * reference; a differing raw hover result is tolerated for up to
 * DWELL_JITTER_TOLERANCE_MS before the committed target actually switches
 * (and progress resets to 0 only at that point) -- so a brief flicker never
 * transfers accumulated time onto a different element. Landing on a target
 * from NOTHING commits immediately (no debounce) -- only already-in-progress
 * dwell is protected from jitter; onset is never artificially delayed.
 *
 * Reset/cancel triggers (any of): cursor leaves the target, tracking is
 * lost (status leaves "tracking"), the target is removed from the DOM,
 * becomes disabled/hidden, a blocking modal opens, hand control is
 * disabled, another gesture begins on the primary hand for a DIFFERENT,
 * non-dwell target (select armed/dragging) or two-hand zoom becomes active,
 * or the browser tab becomes hidden (`document.visibilitychange`) --
 * returning to the tab always requires a fresh dwell, never resumes
 * mid-progress.
 *
 * One action per activation: on completion, activate exactly once
 * (`target.click()`), then require the cursor to leave the target before a
 * new dwell can start on it again.
 */
export const DWELL_DURATION_MS = 2000;
/** ~40% of DWELL_DURATION_MS, per the spec's example (2s normal -> 0.8s accelerated). Applied while `isSelecting` is true over the same dwell target. */
export const DWELL_FAST_DURATION_MS = 800;
export const DWELL_JITTER_TOLERANCE_MS = 150;

/**
 * Marks an element as eligible for dwell activation. Present ONLY on the
 * left sidebar's navigation links (`IconTile`, when used as a nav `<Link>`)
 * -- never applied globally, never to a destructive or action button. A
 * plain HTML attribute (not a React prop) so hit-testing can check it with
 * a simple `element.hasAttribute(...)` without any special-casing per
 * component.
 */
export const DWELL_ELIGIBLE_ATTR = "data-hand-dwell";

export type DwellEventType = "dwellstart" | "dwellcancel" | "dwellactivate";

export interface DwellEvent {
  type: DwellEventType;
  target: HTMLElement;
  timestamp: number;
}

/**
 * CUSTOMIZABLE INTERACTION COLOR -- GOAL 3, Revision 4.
 *
 * One shared setting applied via ONE CSS custom property,
 * `INTERACTION_COLOR_CSS_VAR`, set on `document.documentElement` by the
 * integration layer whenever it changes (a plain style write, independent
 * of camera/tracking lifecycle -- changing it never restarts the camera,
 * resets tracking, or interrupts dwell progress). Every visual that used to
 * hard-code the "engaged" orange (`--warm`) -- the select-engaged cursor/
 * ring, hand-hover highlights, dwell-progress borders, and activation
 * confirmation -- reads this variable instead, so one setting reskins all
 * of them consistently. `DEFAULT_INTERACTION_COLOR` matches the previous
 * hard-coded `--warm` value exactly, so "reset" reproduces the old look.
 */
export const DEFAULT_INTERACTION_COLOR = "#ff9a2e";
export const INTERACTION_COLOR_CSS_VAR = "--hand-interaction-color";

/**
 * CURSOR SHAPE -- Revision 5. Purely a rendering choice for the fingertip
 * cursor's outline/fill (Agent 3's territory): changing it must never move
 * the cursor's anchor point or affect hit-testing -- both already derive
 * solely from `cursor`/`hoverTarget` (ViewportPoint math, untouched by this
 * setting), so this is enforced by construction as long as the shape is
 * applied via CSS on the existing centered dot element (clip-path / border-
 * radius variants), not by swapping in a differently-anchored element.
 * Color swatches in the calibration UI are NOT affected by this setting --
 * they stay square regardless (a separate, fixed UI convention). Dwell's
 * perimeter border continues to trace the TARGET's own shape (e.g.
 * IconTile's rounded corners), never the cursor's shape -- unrelated.
 */
export type CursorShape = "square" | "circle" | "rounded-square" | "diamond";
export const DEFAULT_CURSOR_SHAPE: CursorShape = "circle"; // matches the shape already shipped in Revisions 2-4
export const CURSOR_SHAPES: readonly CursorShape[] = ["square", "circle", "rounded-square", "diamond"];

/** The full hook contract Agent 4's integration layer exposes to Agent 3's overlay + calibration UI (e.g. as `useHandPointer()`). */
export interface HandPointerApi extends HandPointerState {
  /** False until the user explicitly opts in; camera/model are not touched before enable(). */
  enabled: boolean;
  enable(): Promise<void>;
  disable(): void;

  /** Current control region (persisted locally by the integration layer). */
  controlRegion: ControlRegion;
  /** Partial update, e.g. `{ height: 0.4 }` -- merged onto the current region. */
  setControlRegion(patch: Partial<ControlRegion>): void;
  resetControlRegion(): void;

  /** Discrete dwell lifecycle -- see DWELL doc above. Continuous progress is `dwellTarget`/`dwellProgress` on HandPointerState. */
  onDwellEvent(cb: (event: DwellEvent) => void): () => void;

  /** Current interaction color, a CSS hex string (persisted locally). */
  interactionColor: string;
  setInteractionColor(hex: string): void;
  resetInteractionColor(): void;

  /** Current cursor shape (persisted locally). */
  cursorShape: CursorShape;
  setCursorShape(shape: CursorShape): void;
  resetCursorShape(): void;
}
